import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getLegacyProductPath, getProductPath } from "../src/lib/product-url.js";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const productsPath = join(root, "data", "products.json");
const redirectsPath = join(root, "public", "_redirects");
const products = JSON.parse(readFileSync(productsPath, "utf8"));

function catalogSlug(product) {
  if (product.catalog_number) return String(product.catalog_number).toLowerCase();

  return String(product.name || "unknown")
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const redirects = new Map();
for (const product of products) {
  const canonical = getProductPath(product, products);
  const legacy = getLegacyProductPath(product);
  if (legacy && legacy !== canonical) redirects.set(legacy, canonical);

  const catalog = `/products/${catalogSlug(product)}/`;
  if (catalog !== canonical) redirects.set(catalog, canonical);
}

const lines = [
  "# Generated by scripts/generate_redirects.mjs from data/products.json.",
  "# Do not edit by hand.",
  "",
  ...[...redirects.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([from, to]) => `${from} ${to} 301`),
  "",
];

mkdirSync(dirname(redirectsPath), { recursive: true });
writeFileSync(redirectsPath, lines.join("\n"));
console.log(`Generated ${redirects.size} redirects in public/_redirects`);
